var x=[];
x.push(5);
x.push("Eftekher Ali Efte");
x.push(19.5456);
console.log(x);

var a="Eftekher";
var b=a.split("");
console.log(b);
var c=a.split();
console.log(c);
var f="Bangladesh is my country";
d=f.split("n");
console.log(d);
var g=f.split(" ");
console.log(g);
var h="Bangladesh,china,India,pakistan";
console.log(h);
var i=h.split(",");
console.log(i);
var j=i.toString();
console.log(j);
var k=i.join("/");
console.log(k);
var m=i.join(" ");
console.log(m);
var n=m.concat(h);
console.log(n);